#!/bin/bash
# written by Darrow Hartman Sep 30 2021

echo "Starting up!"

read -p "Enter project name: " project
read -p "Enter file name (no .css/.js/.html.j2!): " filename

echo "Filetype options:
  - .css
  - .html.j2
  - .js
  - .py
"
read -p "Enter Filetype: " filetype

cd "$project"
