#!/bin/bash
# written by Darrow Hartman Sep 30 2021

read -p "Enter project name: " project
#making project

mkdir "$project"
cd "$project"
mkdir "templates"

# new files

touch "app.py"
touch "runflask.bat"
cd "templates"
touch "index.html.j2"
touch "base.html.j2"

# add code

read -p "Add Bootstrap? (y/n)" bootstrap

if [[ "$bootstrap" =~ ^([yY][eE][sS]|[yY])$ ]]
then
  echo "

  <!DOCTYPE html>
  <html lang=en dir=ltr>
    <head>
      <meta charset=utf-8>
      <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' integrity='sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T' crossorigin='anonymous'>
      <title>
        {% block title %} title empty {% endblock %}
      </title>
    </head>
    <body>
      {% block body %} body empty {% endblock %}
      <script src='https://code.jquery.com/jquery-3.3.1.slim.min.js' integrity='sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo' crossorigin='anonymous'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js' integrity='sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1' crossorigin='anonymous'></script>
  <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js' integrity='sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM' crossorigin='anonymous'></script>
    </body>
  </html>

  " > base.html.j2
else
  echo "

  <!DOCTYPE html>
  <html lang=en dir=ltr>
    <head>
      <meta charset=utf-8>
      <title>
        {% block title %} title empty {% endblock %}
      </title>
    </head>
    <body>
      {% block body %} body empty {% endblock %}

    </body>
  </html>

  " > base.html.j2
fi



echo "
{% extends 'base.html.j2' %}

{% block title %}
"$project"
{% endblock %}

{% block body %}
<p>code running on "$project"!</p>
{% endblock %}
" > index.html.j2




cd ..
printf "export FLASK_APP=app.py && export FLASK_ENV=development \n flask run" >> runflask.bat
printf "from flask import Flask, render_template \napp = Flask(__name__) #this has 2 underscores on each side \n \n@app.route('/') \ndef index(): \n\treturn render_template('index.html.j2') \n " >> app.py

# init server

chmod 777 runflask.bat

echo "fully completed, happy coding"
echo "link: http://127.0.0.1:5000/"

./runflask.bat
